name: .NET Core CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [2.2.401, 3.0.100-preview9-014004]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: rojepp/setup-dotnet@fix_dotnet_root
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dotnetsay
      run: dotnet tool install dotnetsay --tool-path dotnetsay
    - name: Run dotnetsay
      if: runner.os != 'Windows'
      run: dotnetsay/dotnetsay
    - name: Run dotnetsay
      if: runner.os == 'Windows'
      run: dotnetsay/dotnetsay.exe

