name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: rojepp/setup-dotnet@fix_dotnet_root
      with:
        dotnet-version: 2.2.402
    - name: Display DOTNET_ROOT
      run: ls $DOTNET_ROOT/..
    - name: Install dotnetsay
      run: dotnet tool install dotnetsay --tool-path dotnetsay
    - name: Run dotnetsay
      run: dotnetsay/dotnetsay
  #    env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
  #      DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.402/x64    
